version: '3.4'

services:

  gateway:
    image: ${DOCKER_REGISTRY-}nolt-gateway
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    depends_on:
      - restaurants
      - customers
    ports:
      - "8082:8082"
    restart: always
    volumes:
      - source: ~/.m2
        target: /root/.m2
        type: bind