openapi: 3.0.0
info:
  description: A food ordering and delivery platform
  version: "1.0.0"
  title: Nolt API

paths:
  /customer-service/orders:
    post:
      summary: Submit an order for a customer
      parameters:
        - in: header
          name: X-Customer-Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitOrderRequest'
      responses:
        '201':
          description: Order submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitOrderResponse'
              examples:
                application/json:
                  value:
                    orderId: 9c26f0e6-7f1d-480c-8ca5-3f9c21208b96
  /customer-service/orders/{orderId}:
    get:
      summary: Gets an order for a customer
      operationId: get-customer-order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
        - name: X-Customer-Id
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderResponse"
              examples:
                application/json:
                  value:
                    orderId: 8488e986-b848-4e87-891a-43252f36ba0c
                    customerId: 018777ce-8730-46ae-800c-9a1e950e05c0
                    state: Submitted
                    orderItems:
                      - menuItemId: burger
                        quantity: 10
                        notes: no coleslaw
components:
  schemas:
    GetOrderResponse:
      required:
        - orderId
      properties:
        id:
          type: string
        customerId:
          type: string
        state:
          type: string
        orderItems:
          items:
            $ref: '#/components/schemas/OrderItem'
    SubmitOrderRequest:
      properties:
        orderItems:
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      properties:
        menuItemId:
          type: string
        quantity:
          type: integer
        notes:
          type: string
    SubmitOrderResponse:
      properties:
        orderId:
          type: string