openapi: 3.0.0
info:
  description: A food ordering and delivery platform
  version: "1.0.0"
  title: Nolt API

paths:
  /customer-service/orders:
    post:
      summary: Submit an order for a customer
      parameters:
        - in: header
          name: X-Customer-Id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitOrderRequest'
      responses:
        '201':
          description: Order submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitOrderResponse'
              examples:
                application/json:
                  value:
                    orderId: 9c26f0e6-7f1d-480c-8ca5-3f9c21208b96
  # TODO - 1. Add contract for get order by id endpoint and run 'mvn compile' in the root directory of the project to generate the sources.
components:
  schemas:
    SubmitOrderRequest:
      properties:
        orderItems:
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      properties:
        menuItemId:
          type: string
        quantity:
          type: integer
        notes:
          type: string
    SubmitOrderResponse:
      properties:
        orderId:
          type: string