version: '3.4'

services:

  restaurants:
    image: ${DOCKER_REGISTRY-}nolt-restaurants
    build:
      context: ..
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
    ports:
      - "7001:8080"
    restart: always
    volumes:
      - source: ~/.m2
        target: /root/.m2
        type: bind